name: smartedu
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.3
  path: ^1.9.0
  video_player: ^2.8.5
  curved_navigation_bar: 1.0.6
  flutter_staggered_grid_view: ^0.7.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_data_connect: ^0.1.3+2
  flutter_native_splash: ^2.4.4
  google_generative_ai: ^0.3.0 # veya güncel sürüm
  http: ^1.4.0
  firebase_storage: ^12.4.6
  flutter_markdown: ^0.6.11
  flutter_pdfview: ^1.2.7+2
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/materials/

flutter_native_splash:
  color: "#D9FBFF"
  image: assets/logo.jpg
  android: true
  ios: true
  fullscreen: true
